### ISSUE TITLE
Animations work without IB?

### ISSUE THREAD

**Issue by ceichin** [IBAnimatable/IBAnimatable#612] opened 2019-05-22 18:36 UTC
When I create the view programmatically, animations don't work. Doing it from the IB and adding an outlet, works fine. Is this the intended behavior?

I created a Single View Project from scratch, and added:
```
class ViewController: UIViewController {

    @IBOutlet weak var squareIB: AnimatableView!
    
    var square: AnimatableView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        square = AnimatableView(frame: CGRect(x: 0, y: 0, width: 100, height: 100))
        square.center = view.center
        square.backgroundColor = .blue
        view.addSubview(square)
    }
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        square.animate(.squeeze(way: .in, direction: .left)) // Does not work
        squareIB.animate(.squeeze(way: .in, direction: .left)) // Works
    }
}
```

Tested it in Xcode 10 and 10.2.1, in both swift 4.2 & 5.

**Comment by ceichin** [comment] 2019-05-22 19:23
I just noticed that adding `square.configureAnimatableProperties()` before calling the animations works.

**Comment by mingsai** [comment] 2019-09-27 02:20
Can you close the issue? Sounds like the problem is solved. Thanks for the tip.

**Closed as completed** 2019-09-27 06:15 UTC
