### ISSUE TITLE
BorderSide

### ISSUE THREAD

**Issue by DonBaronFactory** [IBAnimatable/IBAnimatable#224] opened 2016-06-17 19:32 UTC
If I understand BorderSide correctly it's there to define which border should be displayed with the given BorderColor and -Width.

my issue is that I don't manage to make it work, neither by setting the String in IB, nor by setting the variable in the keypath, nor by setting the String programatically... besides that, I also noticed that every parameter I set in IB is automatically set as keypath, but for borderSide...

any help?

PS: using a UIView and Swift 2.2

**Comment by tbaranes** [comment] 2016-06-17 19:51
`BorderSide` allows you to choose which border will be displayed, but by default, it will display all. For example, here how to set a border to a view programatically:

``` swift
let view = AnimatableView(frame: CGRect(x: 100, y: 100, width: 100, height: 100))
myView.addSubview(view)
view.borderWidth = 2
view.borderColor = UIColor.purpleColor()
```

Also, after a second check in the interface builder, I can confirm everything is working as expected. The key path is well-settled:

<img width="258" alt="screen shot 2016-06-17 at 21 42 22" src="https://cloud.githubusercontent.com/assets/1402212/16162538/659a22a6-34d4-11e6-95a0-268849779cb0.png">

In order to help you, we will need more information about your setup:
- What is exactly not working? 
- Did you try to set others features in your view? Mask, Rotate...
- Do you have any screenshots of your setup? Or just what / how did you set your view?

You can take a look to the storyboard in demo app (it's implementing almost all the features designable), or the playground to have an advanced example of how to use IBAnimatable programatically.

**Comment by DonBaronFactory** [comment] 2016-06-17 20:02
Thanks for your answer, let me be more specific...

The border color and width work perfectly (as all other parameters). But when I set borderSide to Bottom the UIView is still displayed with all 4 borders rather than as expected just with the one mentioned ....

I checked the demo app, but haven't found any component (yet) which uses borderSide...

Checking the enum for borderSide, I just need to provide a String like "Border" (without quotes in IB of course) or a comma sep list of sides I want to be displayed.... 

What am I missing?

**Comment by tbaranes** [comment] 2016-06-17 20:07
What did you write in the `border side` field? The supported strings are the following: `Top`, `Bottom`, `Left`, `Right`. If you want to combine some, you have to separate each of them by a `,`. 

<img width="274" alt="screen shot 2016-06-17 at 22 06 50" src="https://cloud.githubusercontent.com/assets/1402212/16163126/d2f8ff2c-34d7-11e6-84b8-6f8309f48bf3.png">
<img width="257" alt="screen shot 2016-06-17 at 22 06 54" src="https://cloud.githubusercontent.com/assets/1402212/16163135/e06eb5ca-34d7-11e6-9354-cdfd91bc87a5.png">

**Note:** if the `border side` field text isn't supported, we will fallback on the default behaviour (draw the four borders). Sadly, we can't throw any errors due to `Inspectable` / `Designable` limitations...

@JakeLin It would be interested to add an example of this in the demo app, didn't know there wasn't one.

**Comment by DonBaronFactory** [comment] 2016-06-17 20:13
did exactly like you, with Capital B for Bottom etc on an UIView, somehow it doesn't wanna work, neither as IBDesignable directly in the Storyboard, nor when running the app ... weird

**Comment by tbaranes** [comment] 2016-06-17 20:17
Can you paste some screenshots / code or sending a sample in order to reproduce your issue? I got any _anormal_ behaviour by playing around in the demo app.

EDIT: Also tried in playground `view.borderSide = "Top,Bottom"`, everything is working well...

**Comment by tbaranes** [comment] 2016-06-17 20:22
One more question, which version of `IBAnimatable`? The released last version or the current master?

**Comment by DonBaronFactory** [comment] 2016-06-17 20:24
Following the screenshots:

![screen shot 2016-06-17 at 22 21 36](https://cloud.githubusercontent.com/assets/10096944/16163522/078a40fa-34da-11e6-87d4-a996a3397e06.png)

![screen shot 2016-06-17 at 22 21 59](https://cloud.githubusercontent.com/assets/10096944/16163524/0f2666cc-34da-11e6-86a3-371b2b27f5ad.png)

The installed version is 2.2.0

**Comment by tbaranes** [comment] 2016-06-17 20:33
I though it was a bug created in the 2.2.0, but even after rollback to this version, it's still working as expected.
Can you try to reproduce it using IBAnimatable 2.3.0 or the master code to confirm that it's not related to 2.2.0? 

EDIT: If it's still not working, I'm really interesting in your sample in order to reproduce that bug, can you upload or send it?

**Comment by DonBaronFactory** [comment] 2016-06-17 20:37
adding `pod 'IBAnimatable', '2.3.0'` to my podfile gets rejected

**Comment by DonBaronFactory** [comment] 2016-06-17 20:38
XCode 7.3.1

**Comment by tbaranes** [comment] 2016-06-17 20:39
It's `2.3`, my bad. Otherwise, you can directly do `pod 'IBAnimatable'` in order to have the latest version or even try to reproduce the bug in the sample project.

**Comment by DonBaronFactory** [comment] 2016-06-17 20:44
weird, installed the pod with `pod 'IBAnimatable'`and `pod install` just a few hours ago and received version 2.2, using `pod update` right now I got version 2.3 installed... Anyway, the borders are displayed correctly now.

Many thanks @tbaranes for being so responsive and helpful!! it's a great framework I already don't wanna miss  anymore

PS: Just found out that `pod install` (version 1.0) does not update the master repos unless explicitly called with `pod update`, I guess that was my problem not getting latest version

**Comment by tbaranes** [comment] 2016-06-17 20:48
Happy that we got your issue solved and that you liked that framework. Enjoy! 🎉 

PS: For the history, that issue was introduced in 2.2, and fixed in 2.3. It's was reported in #179. Just find out that issue..

**Closed as completed** 2016-06-17 20:48 UTC

**Comment by DonBaronFactory** [comment] 2016-06-17 20:53
See I didn't have IBAnimatable installed before, it was the first time I installed it... pod must kinda cache the master repos and only update the list once called with `update`.. it took a few minutes to update it's cache before at last finding and installing 2.3... 

although I searched the issues for borderSide, I must have missed it (maybe because of the title being about textfield)... mea culpa

**Comment by JakeLin** [comment] 2016-06-18 12:37
@cre8it it is a little bit late, but do have used `BorderSide` in our demo app.

<img width="1196" alt="screen shot 2016-06-18 at 10 24 22 pm" src="https://cloud.githubusercontent.com/assets/573856/16170878/81791b50-35a4-11e6-9e61-45eed9ca2a5e.png">

But I think we should do it more specific like what we are doing for transitions. e.g. We can use particular ViewController for demonstrating the each designable feature.

@tbaranes thanks for your quick response. You make this project awesome 👍

**Comment by DonBaronFactory** [comment] 2016-06-18 14:08
It is indeed a bit cumbersome to search for a view which implements the borderSides, but frankly, the concept is perfectly explained and imho doesn't need any extra explanation nor visualisation. I just went searching for it in the demo app because it wasn't working and thought it was a mistake of how I typed in the parameters, so I wanted to check the correct syntax... It turned out my syntax was correct but my cocoapod played games with me ;)

This project is indeed awesome and the responsiveness and commitment of @tbaranes makes it even greater... thanks @JakeLin for the great work
