### ISSUE TITLE
AnimatableLabel slideFade(in,right) is not working in TableViewCell in iOS 10

### ISSUE THREAD

**Issue by digidhamu** [IBAnimatable/IBAnimatable#339] opened 2016-09-24 07:42 UTC
There is an issue when to use `slideFade` or `slide` animation inside a `TableViewCell` in iOS 10.

There are not problems if we don't use those animations within a `TableViewCell` . Or there are not problems in iOS 9.

------Origin message---------------------
I am currently migrating to version 3.0 and observed that AnimatableLabel with _animationType = "slideFade(in,right)" not working when I have configured in IB but pop(1) is working. Could you please advise.

<img width="281" alt="screen shot 2016-09-24 at 1 10 09 pm" src="https://cloud.githubusercontent.com/assets/9908852/18806918/547555a0-8258-11e6-94e7-90f96379676a.png">

**Comment by tbaranes** [comment] 2016-09-24 07:53
I just try it in the demo app, it seems to be working as expected for me. Here my setup:

<img width="387" alt="screen shot 2016-09-24 at 09 51 58" src="https://cloud.githubusercontent.com/assets/1402212/18806986/8dd0ee48-823c-11e6-95ff-aa50ae1f92b4.png">

Few questions in order to reduce the potential errors:
- What's not working? Is it the Fade? The slide? No animation at all?
- Did you try to use `slide(in,right)` instead?

**Comment by digidhamu** [comment] 2016-09-24 08:07
No animation at all.
I have even tried `slide(in,right)` this and not working.

Which screen of Demo app you have tried? Let me try as well.

**Comment by tbaranes** [comment] 2016-09-24 08:09
I just added an `AnimatableLabel` without any customisation (just few constraints leading / top) in the root controller of the `Main.storyboard`, then added your animation and delay. Let me know how it goes for you!

Also, are you using CocoaPods? Carthage?

**Comment by tbaranes** [comment] 2016-09-24 08:15
One more thing, are you able to reproduce that in a sample project? If so, can you send it to us?

**Comment by digidhamu** [comment] 2016-09-24 08:16
Cocoapods and but it was working nicely with same constraints before.
Sure I will create sample project soon and send you soon.

**Comment by digidhamu** [comment] 2016-09-24 08:17
Which screen of Demo app you have tried?

**Comment by tbaranes** [comment] 2016-09-24 08:25
Just added a label on the top of the first screen, not sure if there's an example using `slideFade` directly in the interface builder.

<img width="442" alt="screen shot 2016-09-24 at 10 24 31" src="https://cloud.githubusercontent.com/assets/1402212/18807188/1977f438-8241-11e6-87f7-8ec74b4100c9.png">

**Comment by digidhamu** [comment] 2016-09-24 10:38
I can see working on the home screen. But when I add label into TableViewCell not working. Please see the attached sample project as you requested. Please advise.
[IBAnimatableLabelTest.zip](https://github.com/IBAnimatable/IBAnimatable/files/491063/IBAnimatableLabelTest.zip)

**Comment by JakeLin** [comment] 2016-09-25 02:24
@dhamukrish I have tried out your demo code, it is not working inside the table view cell. But Pop animation is working fine, I can see the `x` was right to be `375` (on iPhone 6), but the animation doesn't run. I am not sure it is an issue of iOS 10 or not. Will have more investigations. On the other hand, if you have a static number of cell item, you can use stack view like the demo app does. "Demo Application" -> "Create Account" then you will see the effect.

**Comment by digidhamu** [comment] 2016-09-25 02:29
@JakeLin Thanks for your update. I would rather wait for your fix at this moment.

**Comment by JakeLin** [comment] 2016-09-25 04:48
@dhamukrish thanks, I have tried it in iOS 9, it is working as expected.

![slidein](https://cloud.githubusercontent.com/assets/573856/18813036/f4d7ef7e-832c-11e6-89d7-5ec5960ad755.gif)

I don't know it is a bug of iOS 10 or Apple intended to change the implementation for `UIView.animate`.

```
UIView.animate(withDuration: duration, delay: delay, usingSpringWithDamping: damping, initialSpringVelocity: velocity, options: [],
      animations: {
        self.transform = CGAffineTransform.identity
        self.alpha = alpha
      },
      completion: { completed in
        if completed {
          completion?()
        }
    })
```

But it is still working fine when we do not put it in a table view cell. I am busy on preparing a talk for [YOW Connected](https://a.confui.com/-n0VH09na) in about 10 days. Probably, I have to focus on the talk and try to fix this issue after that, sorry for the delay. 

I have some idea if you would like to give it a go. We may need to use the new API `UIViewPropertyAnimator` for iOS 10, I have played around it before in https://github.com/JakeLin/SaveTheDot project. Please let me know if you have any questions, thanks.

**Comment by digidhamu** [comment] 2016-09-25 15:26
Thanks for your update and can wait for your fix.

**Comment by rscodra** [comment] 2016-12-29 15:07
Can confirm this is still persisting, at least in my app. Did anyone work on it, any suggestions?

**Comment by JakeLin** [comment] 2016-12-30 23:42
@sambing sorry, I haven't got time to look at this issue. Can you confirm this issue only happen in iOS 10 not iOS 9? It looks like an iOS 10 specific issue. Thanks.

**Comment by digidhamu** [comment] 2016-12-31 07:56
I have just tested and I can see still see the same issue on iOS 10 but not on iOS9. Basically the issue is that when I add AnimateLabel inside UITableViewCell with animation type slideFade(in,right).

**Comment by JakeLin** [comment] 2016-12-31 22:57
@dhamukrish I investigated this issue before and found out it is an iOS 10 specific issue. It's not easy to find out why. Apple may change the lifecycle for `UITableViewCell`. I suggest you use `StackView` for `slideFade(in,right)` animation for that moment.

**Comment by digidhamu** [comment] 2017-01-01 14:05
Ok sure

**Comment by rscodra** [comment] 2017-01-02 23:06
@JakeLin iOS 10 only. Before i read your comment i simply animated the views programmatically and that works fine.

**Comment by JakeLin** [comment] 2017-01-02 23:54
@dhamukrish Would you please try @sambing 's approach? Thanks for your feedback @sambing .

**Comment by rscodra** [comment] 2017-01-03 08:05
@JakeLin Thank you.

**Comment by phimage** [comment] 2017-03-25 12:24
If we look at `animate` stack call if `auto` = true (animate on layoutSubviews)
on ios10 we see 
- UIView.layoutSubviews
- **UIView.performWithoutAnimation**
- UITableView._performWithCachedTraitCollection
- UIView.layoutSublayers

on ios9
- UIView.layoutSubviews
- UIView.layoutSublayers


Just to try, enqueueing the animation to main queue allow to play the animation
```swift
 func autoRunAnimation() {
    if autoRun {
        autoRun = false
        DispatchQueue.main.async { [unowned self] in
            self.animate()
        }
    }
   }
```
but the translation to set view at start position of animation is visible

So maybe there is another moment to launch the animation automatically


As a workaround I call an animation in my 
 ` func tableView(_ tableView: UITableView, willDisplay cell: UITableViewCell, forRowAt indexPath: IndexPath) {`
  the stack of this function has `_performWithCachedTraitCollection` like but not **UIView.performWithoutAnimation**

**Comment by JakeLin** [comment] 2017-03-27 05:33
@phimage thanks for your workaround/solution for that issue. Do you know why iOS 10 changed the behaviour of that for adding 'UIView.performWithoutAnimation'? Because `autoRunAnimation()` method is used for everywhere, I think it is too big to change it to have  `DispatchQueue.main.async` inside. We may suggest the user use your solution for the animation within table view cell.

**Comment by tbaranes** [comment] 2020-03-31 14:06
Closing this now since it's been a while, let us know if you still have any issues.
By the way, I do think we should drop iOS10 support with next release.

**Closed as completed** 2020-03-31 14:06 UTC
Labels: type: bug, help wanted
